include ../scripts/env.mk

SUB_DIRS    += app 
LIB_DIR     += 
LIBS        += 

INCLUDE_DIR := 
INSTALL_DIR := 
SOURCES_DIR := 
TARGET      :=



CFLAGS := $(CFLAGS) $(INCLUDE_DIR)

include ../scripts/rule.mk