include ../../scripts/env.mk

SUB_DIRS    +=  
LIB_DIR     += 
LIBS        += 

INSTALL_DIR := 
SOURCES_DIR := src
TARGET      := main.exe

INCLUDE_DIR += -I ./include
INCLUDE_DIR += 

include ../../scripts/rule.mk
	